### ISSUE TITLE
localhost and IPv4

### ISSUE THREAD

**Issue by wanneut** [artefactual-labs/am-packbuild#106]
When installing archivematica gunicorn listens on 127.0.0.1:7400 only.
But nginx is configured as reverse Proxy for http://localhost:7400
Which resolves in the most cases (e.g. in CentOS 7) to http://[::1]:7400

This could be solved by the user by letting nginx explicitly connect to IPv4:
```
<     proxy_pass http://localhost:7400;
---
>     proxy_pass http://localhost4:7400;
```
in /etc/nginx/conf.d/archivematica-dashboard.conf and /etc/nginx/conf.d/archivematica-storage-service.conf

Nicer way would be to make gunicorn to listen to all localhost addresses (including IPv6).
IMHO binding to every address to which a domain resolves is a much better approach to handle different addresses behind one domain and makes configuration more easy.

**Comment by sevein** [comment]
@scollazo thanks for submitting #113. @wanneut can you take a look?

We should probably leave this issue open anyways so at some point in the future we change the [default in Gunicorn](https://github.com/artefactual/archivematica/blob/5ed067280a36711d6e1aa6e628ad3ca11d7a1cbe/src/dashboard/install/dashboard.gunicorn-config.py#L12-L13). To be clear, would this be as easy as changing the default from `127.0.0.1:8002` to `localhost:8002`? If so perhaps we should do this before the AM17 release.

```
# http://docs.gunicorn.org/en/stable/settings.html#bind
bind = os.environ.get('AM_GUNICORN_BIND', '127.0.0.1:8002')
```

**Comment by wanneut** [comment]
gunicorn cannot resolve IPv6 hostnames:
https://github.com/benoitc/gunicorn/blob/76eaa0805b0d2d19b8e6f0690461ddaceb80e16f/gunicorn/sock.py#L132
https://github.com/benoitc/gunicorn/blob/19.4.5/gunicorn/util.py#L217
The problem is, that gunicorn expects (like many python software) everything what is no IPv6 address to be IPv4. Even if you try to bind to localhost6 gunicorn wont bind to IPv6. Instead it will fail, because it can not resolve localhost6 to an IPv4 address.

Main problem is that everybody copys this example does not handle IPv6:
https://docs.python.org/3/howto/sockets.html
Here is an example how to do it right: 
https://docs.python.org/2.5/lib/socket-example.html

Instead gunicorn expects a list with plain IPs like this:
bind = [ '[::1]:1337', '127.0.0.1:1337' ]
If you want to control this via environment variables you would have to do some parsing.

**Comment by wanneut** [comment]
A other workaround would be to misuse pythons dynamic typing:
`bind = os.environ.get('AM_GUNICORN_BIND', [ '[::1]:8002', '127.0.0.1:8002' ])`


Or a more advanced solution would be:
`bind = os.environ.get('AM_GUNICORN_BIND', '[::1]:8002 127.0.0.1:8002').split(' ')`
This would allow users to use more than one socket by separating them with spaces. A feature that is also useful in other scenarios than dualstack.
Since domain names with spaces aren't allowed this should not be a problem.

**Comment by sevein** [comment]
> bind = os.environ.get('AM_GUNICORN_BIND', '[::1]:8002 127.0.0.1:8002').split(' ')

Yeah this is what I was thinking. I believe we've used this approach in a different place recently. `ALLOWED_HOSTS` in Django if I remember correctly.

Thanks again.
