### ISSUE TITLE
Packaging for Columbia

### ISSUE THREAD

**Issue by nickwilkinson** [artefactual-labs/am-packbuild#108]
Any changes from https://github.com/artefactual-labs/am-packbuild/commits/dev/build-dev-1.8-packages that are needed should be merged to master.

**Comment by scollazo** [comment]
There was a bugfix, but it's not needed in master, so the branch has been deleted.

**Comment by scollazo** [comment]
Current packages do the common install (with elasticsearch). Once AM is installed, the default behavior can be changed by editing the /etc/default/archivematica-* files. If that's not enough, and we want a way to choose between common and indexless installs, two options came to my mind:
 - Create different am packages
 - For ubuntu, we can create a dialog that is shown to the user at install time, so they can select witch kind of install they want.
