### ISSUE TITLE
Problem: version and release are missing in rpm specs

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am-packbuild#118]
I'm not entirely sure if this is a bug but it looks like it. I'm downloaded https://packages.archivematica.org/1.7.x/centos/archivematica-1.7.0-rc4.src.rpm to take a look at the final spec and this is what I am seeing:

```
$ grep "Version\|Release" package.spec
Version: %{rpmversion}
Release: %{rpmrelease}
```

Is this the expected outcome?

There are no globals or defines in the spec file.

**Comment by scollazo** [comment]
The globals are defined in the Makefile, and can be overrided by passing arguments in the command line ilke:
 
    make BRANCH=qa/1.x VERSION=1.8.0 RELEASE=45
