### ISSUE TITLE
Problem: unable to update python-minimal in xenial

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am-packbuild#119]
Related: https://github.com/artefactual-labs/ansible-archivematica-src/issues/178.

- [x] https://github.com/artefactual-labs/am-packbuild/pull/122 (xenial)
- [x] https://github.com/artefactual-labs/am-packbuild/pull/135 (trusty)
- [x] https://github.com/artefactual-labs/am-packbuild/pull/130 (rpm)

Also a change is required in the docs repo:
- [x] https://github.com/artefactual/archivematica-docs/issues/100

**Comment by sevein** [comment]
We have now all the PRs in place for this issue.
It's also going to require a small update in the docs: https://github.com/artefactual/archivematica-docs/issues/100.

**Comment by scollazo** [comment]
We also need to reflect the new path for the venvs in the docs:

https://github.com/artefactual/archivematica-docs/search?utf8=%E2%9C%93&q=%22%2Fusr%2Fshare%2Fpython%22&type=

**Comment by sevein** [comment]
Totally good point @scollazo!
