### ISSUE TITLE
Problem: acceptance-test have to be run against rpm and deb packages

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/am-packbuild#131]
We are building deb/rpm packages, and testing that the install succeed.

We need to run the acceptance tests, to be sure that after installing the packages, the system works as expected.

**Comment by sevein** [comment]
@scollazo is working on this.

**Comment by jrwdunham** [comment]
Hey @scollazo lemme know if you need any help with this. The `behave` command at https://github.com/artefactual/archivematica/issues/942#issuecomment-370983767 should run all the features that are expected to pass on AM 1.7.
