### ISSUE TITLE
Problem: rpm-testing does not use a fixed IP address

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am-packbuild#133]
@scollazo suggested to use one here: https://github.com/artefactual-labs/am-packbuild/pull/120#pullrequestreview-105569305.

**Comment by scollazo** [comment]
Also, the image should use private networking, instead of public ( https://github.com/artefactual-labs/am-packbuild/pull/120#discussion_r176013429 )

**Comment by sevein** [comment]
Fixed in #120.
