### ISSUE TITLE
Problem: version of MediaConch required by AM17 isn't provided yet

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am-packbuild#141]
See https://github.com/artefactual/archivematica/pull/995.

I believe there's also another PR coming soon that will include the latest release available.

IIRC, we need to update the spec with the proper version constraint and we need to publish the new packages in our repositories.

CC @jrwdunham

**Comment by jrwdunham** [comment]
- [AM issue 1006](https://github.com/artefactual/archivematica/issues/1006) asserts need for MediaConch v. 18.03
  - [AM PR 1010](https://github.com/artefactual/archivematica/pull/1010) should install MC 18.03 on stable/1.7.x Ansible and Docker installs.
  - [AM PR 1009](https://github.com/artefactual/archivematica/pull/1009) should install MC 18.03 on qa/1.x Ansible and Docker installs.

Cf. https://mediaarea.net/MediaConch/Download

**Comment by scollazo** [comment]
Mediaconch v18.03 has been added to ubuntu-externals and centos-extras repo.

More info about adding packages to repositories can be found in https://github.com/artefactual-labs/am-packbuild/pull/142

**Comment by sevein** [comment]
Thank you, this is awesome!

CC @jrwdunham @ross-spencer @ablwr
