### ISSUE TITLE
Problem: RPM packages don't have a changelog

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/am-packbuild#145]
RPM packages should have a changelog that, at least, tells wich sha1 commit they have been built from.

Related to #118

**Comment by sevein** [comment]
This sounds like a nice to have but is it a blocker?

**Comment by scollazo** [comment]
Fixed in https://github.com/artefactual-labs/am-packbuild/commit/7d0527383fb0d11ddd2538c2ba4130f1b293b0ab
