### ISSUE TITLE
rpm: Set up elasticsearch client in gunicorn's wsgi.py

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/am-packbuild#15]
We can update wsgi.py as we do [here](https://github.com/artefactual/archivematica/blob/dev/docker/src/dashboard/src/wsgi.py)

**Comment by sevein** [comment]
Here's the fix: https://github.com/artefactual/archivematica/pull/426.
Once it's merged we'll have to rebuild the packages before closing this issue.

**Comment by sevein** [comment]
Fixed!
