### ISSUE TITLE
problem: rpm version numbers for release candidates are wrong

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/am-packbuild#181]
Release candidate rpm packages are being built as `archivematica-1.7.1-~rc.2.x86_64.rpm` instead of `archivematica-1.7.1~rc.2.x86_64.rpm`

**Comment by scollazo** [comment]
This can be fixed by building them with `VERSION=1.7.1~rc.2`, but that breaks the docker image tag/build

**Comment by mamedin** [comment]
Hi,

In the rpm/archivematica*/Makefile we can use:

- `DOCKER_IMAGE  = $(subst ~,-,"rpmbuild-$(NAME)-$(VERSION)")`

instead of :

-  `DOCKER_IMAGE  = "rpmbuild-$(NAME)-$(VERSION)"`

The problem happens because docker doesn't allow the character "~" as image name. Changing this character in the `DOCKER_IMAGE` variable fixes the issue.

**Comment by mamedin** [comment]
I suggest to use this long version number:

```
Release Tag	Explanation
pkg-0.9.2-0.1.beta1%{?dist}	(this is the Fedora package for 0.9.2beta1, as above)
pkg-0.9.2-0.2.beta1%{?dist}	(this is a new patch on top of 0.9.2beta1)
pkg-0.9.2-0.3.beta2%{?dist}	(this is after upgrading to 0.9.2beta2)
pkg-0.9.2-0.4.beta3%{?dist}	(this is after upgrading to 0.9.2beta3)
pkg-0.9.2-0.5.beta3%{?dist}	(this is a new patch on top of 0.9.2beta3)
pkg-0.9.2-0.6.rc1%{?dist}	(this is after upgrading to 0.9.2rc1)
pkg-0.9.2-0.7.rc2%{?dist}	(this is after upgrading to 0.9.2rc2)
pkg-0.9.2-1%{?dist}	(this is after upgrading to 0.9.2 "final", version becomes normal)
pkg-0.9.2-2%{?dist}	(this is a new patch on top of 0.9.2 "final")
```
This is the last example at https://fedoraproject.org/wiki/Package_Versioning_Examples

For example, to build  AM 1.8 beta1 packages, we can use:

*PACKAGE: archivematica
*BRANCH : qa/1.x
*VERSION: 1.8.0
*RELEASE:  0.1.beta1

This way, we got the following packages:

* archivematica-1.8.0-0.1.beta1.src.rpm 
* archivematica-common-1.8.0-0.1.beta1.x86_64.rpm 
* archivematica-dashboard-1.8.0-0.1.beta1.x86_64.rpm
* archivematica-mcp-client-1.8.0-0.1.beta1.x86_64.rpm
* archivematica-mcp-server-1.8.0-0.1.beta1.x86_64.rpm
* archivematica-storage-service-0.13.0-0.1.beta1.x86_64.rpm

For the first AM 1.8 stable version:

*PACKAGE: archivematica
*BRANCH : stable/1.8.x
*VERSION: 1.8.0
*RELEASE:  1

The official stable packages will use a simple version number.

**Comment by scollazo** [comment]
We are using 
```
archivematica-mcp-client-1.9.0~rc.1-+12.g964dbad.x86_64
archivematica-common-1.9.0~rc.1-+12.g964dbad.x86_64
archivematica-mcp-server-1.9.0~rc.1-+12.g964dbad.x86_64
archivematica-dashboard-1.9.0~rc.1-+12.g964dbad.x86_64
archivematica-storage-service-0.14.0~rc.1-+0.gd83d383.x86_64
```
