### ISSUE TITLE
Patch fits-ngserver.sh in RPM/DEB to Use Sensible Java Metaspace Settings

### ISSUE THREAD

**Issue by jpellman** [artefactual-labs/am-packbuild#184]
See a related issue at https://github.com/harvard-lts/fits/issues/177.

When running the "Characterize and extract metadata" microservice in Archivematica 1.7.0 we noticed that we were consistently running into out-of-memory errors on the host due to the Java metaspace growing to a point that all of our RAM was used up due to the fits/nailgun.  I've reported this issue to the FITS folks, but you might want to have the FITS package perform a patch to incorporate the changes I suggested in the linked issue above.

**Comment by sevein** [comment]
Replaced by https://github.com/archivematica/Issues/issues/357.
