### ISSUE TITLE
Problem: AM1.12 packages build fails on xenial (setuptools)

### ISSUE THREAD

**Issue by mamedin** [artefactual-labs/am-packbuild#282]
The dashboard virtualenv fails with:

```
UnsupportedPythonVersion: setuptools requires Python '>=3.5' but the running Python is 2.7.12
```

It fails on dashboard,MCPServer and MCPServer packages because these packages are using the dashboard's python requirements.

**Comment by mamedin** [comment]
Same issue for storage-service build.

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual-labs/am-packbuild/pull/283.
