### ISSUE TITLE
Problem: Error when building SS v0.17.0 packages on Ubuntu (ldap)

### ISSUE THREAD

**Issue by mamedin** [artefactual-labs/am-packbuild#284]
Same issue than https://github.com/artefactual-labs/am-packbuild/issues/258

The patch (that removes ldap support) needs to be updated or the SS ldap support should be restored.

This issue will happen on every release, so it is desirable to remove the patch from am-packbuild.

**Comment by sevein** [comment]
Fixed in b55d0f63b1b369e4c5a71be13d7deeb6bb9ea7b9.
