### ISSUE TITLE
sudo problems with centos

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/am-packbuild#37]
By default, CentOS 7 enables `requiretty` for sudo access, and that make some mcp-client scripts fail early.

It can be disabled per-user, with `!requiretty`.

**Comment by sevein** [comment]
So we need to edit sudoers from one of our packages?

**Comment by sevein** [comment]
@scollazo, I suspect we're not going to need this in AM 1.7: https://github.com/artefactual-labs/am-packbuild/blob/master/rpm/archivematica/package.spec#L241-L251. See #567 for more details.

```
# Configure sudoers and check validity
set -e
tmp="/tmp/archivematica-sudoers"
real="/etc/sudoers.d/archivematica"
echo "archivematica ALL=NOPASSWD:/bin/mv,/bin/chown,/bin/chmod,/usr/bin/find,/usr/bin/gs,/usr/bin/inkscape" > "${tmp}"
visudo -c -f ${tmp}
if [ "$?" -eq "0" ]; then
  chown root:root "${tmp}"
  chmod 440 "${tmp}"
  mv ${tmp} ${real}
fi
```
