### ISSUE TITLE
Problem: SS 0.11 packages need tweaks

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am-packbuild#42]
Changes are being made in SS 0.11 that will likely affect the way packages are built, e.g. new environment variables, WhiteNoise, etc...

Find all the details in the following links:
- https://github.com/artefactual/archivematica-storage-service/pull/217
- https://github.com/artefactual/archivematica-storage-service/pull/218
- https://github.com/artefactual-labs/ansible-archivematica-src/pull/119

**Comment by scollazo** [comment]
@sevein , I think that after #59 , all those issues have been addressed.  Any concerns before closing this?

**Comment by sevein** [comment]
This is good, thank you so much! Too bad that we don't have commits or PRs pointing to this issue. Next time!
