### ISSUE TITLE
Problem: siegfried 1.7.3 rpm package won't install

### ISSUE THREAD

**Issue by jhsimpson** [artefactual-labs/am-packbuild#43]
This repo builds a new version of siegfried (version 1.7.3).  The package is uploaded to https://packages.archivematica.org/1.6.x/centos-extras.

The version of this package on that server right now can't be installed on a Centos 7.x machine.  This has been tested on 5 machines so far - same error each time.  Whether it is a fresh installation or an upgrade from siegfried 1.6.7, the same errors show:

`
warning: group 1000 does not exist - using root
warning: user 1000 does not exist - using root
warning: group 1000 does not exist - using root
error: unpacking of archive failed on file /usr/share/siegfried/release-notes.xml;599d92c7: cpio: read
`

I am guessing that user 1000 and group 1000 means the 'archivematica' user?  I think it should be possible to install siegfried without first installing Archivematica.  The release-notes.xml, however, appear to just be missing from the package?

**Comment by scollazo** [comment]
Fixed in 58549e5401bfb2480edf3547a21c500eb13d0d4d , the new package has been uploaded to the repo
