### ISSUE TITLE
Problem: Dashboard and Storage Service rpm's missing gunicorn config file

### ISSUE THREAD

**Issue by jhsimpson** [artefactual-labs/am-packbuild#44]
https://github.com/artefactual/archivematica/blob/stable/1.6.x/src/dashboard/install/dashboard.gunicorn-config.py

This is a config file that should get copied into /etc/archivematica/dashboard-gunicorn-config.py.  The systemd service definintion for the dashboard should be copied from this file in the rpm:
https://github.com/artefactual/archivematica/blob/stable/1.6.x/src/dashboard/install/archivematica-dashboard.conf

Also, the nginx config file is not getting used (from https://github.com/artefactual/archivematica/blob/stable/1.6.x/src/dashboard/install/dashboard.conf)

On an rpm install of 1.6.1, the systemd config file has the timeout value and number of workers value hardcoded, and the dashboard-gunicorn-config.py file is missing.  The same isue exists for the storage service 0.10.1 rpm.

**Comment by scollazo** [comment]
Gunicorn and systemd configs have been updated in b82df2b930b
