### ISSUE TITLE
Problem: there are unneeded packages

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am-packbuild#57]
## HOUSEKEEPING! 🚿 

Outside this repository:
- https://github.com/artefactual/archivematica/tree/qa/1.x/src/dashboard/debian
- https://github.com/artefactual/archivematica/tree/qa/1.x/src/MCPClient/debian
- https://github.com/artefactual/archivematica/tree/qa/1.x/src/MCPServer/debian
- https://github.com/artefactual/archivematica/tree/qa/1.x/src/archivematicaCommon/debian
- https://github.com/artefactual/archivematica-storage-service/tree/qa/0.x/debian

Mainly:
- ~`debs/fido`~
- ~`rpm/fido`~
- ~`rpm/olefile`~
- ~`rpm/six`~

Other possible cleanups:
- ~`files/ss-lib`~
- ~`packbuild.py`~
- ~`packbuild-internal.py`~

**Comment by sevein** [comment]
I filed this issue original to suggest removing the fido packages but I've found others that seem unused. Please add other stuff here that needs to be deleted!

**Comment by sevein** [comment]
@scollazo assigned to you because you're the best person at this point to know what can be deleted.

**Comment by sromkey** [comment]
@scollazo can you please confirm that these packages are removed, and then move this to the Done column? Thanks.
