### ISSUE TITLE
Problem: debs don't use mk-install-deps to manage build deps

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/am-packbuild#58]
Currently, they are added to the dockerfile. We should use 
  mk-install-deps -i debian/control

**Comment by jhsimpson** [comment]
@scollazo can you provide more detail about this issue?  Are you talking about dependencies like the appraisal tab and transfer browser, in archivematica?  Or are you talking about different dependencies?

**Comment by scollazo** [comment]
No, this is related to debian dependencies, currently we have to add them twice, in the dockerfile and in the debian/control file. The one about js libraries is #47

**Comment by scollazo** [comment]
This is happening again with storage-service, due to the rng-tools dependency:
`
dpkg-buildpackage: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: rng-tools
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
+ cd /src/src/archivematica-storage-service/
`
