### ISSUE TITLE
Poblem: AM1.7 Nginx config defines config blocks for static assets

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am-packbuild#60]
They need to be deleted.

Related: https://github.com/artefactual-labs/ansible-archivematica-src/issues/145.

**Comment by scollazo** [comment]
This file comes from https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/install/dashboard.conf, so it should be updated there, don't you think?

**Comment by scollazo** [comment]
The file is also in storage-service repo:  https://github.com/artefactual/archivematica-storage-service/blob/qa/0.x/install/storage

**Comment by sevein** [comment]
Ok, they've been updated!
