### ISSUE TITLE
Problem: xenial mcp client package missing config parameters

### ISSUE THREAD

**Issue by jhsimpson** [artefactual-labs/am-packbuild#61]
There are some configuration parameters that are read as environment varaibles in Archivematica 1.7 and above, that are missing from the /etc/default/archivematica-mcp-client.default file.

ARCHIVEMATICA_MCPCLIENT_CLIENT_HOST=
ARCHIVEMATICA_MCPCLIENT_CLIENT_DATABASE=
ARCHIVEMATICA_MCPCLIENT_CLIENT_USER=
ARCHIVEMATICA_MCPCLIENT_CLIENT_PASSWORD=
ARCHIVEMATICA_MCPCLIENT_DISABLE_SEARCH_INDEXING=

ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_MCPARCHIVEMATICASERVER=localhost:4730
ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLIENTASSETSDIRECTORY=/usr/lib/archivematica/MCPClient/assets/
ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_SERVER=/var/run/clamav/clamd.ctl
ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_ARCHIVEMATICACLIENTMODULES=/usr/lib/archivematica/MCPClient/archivematicaClientModules
ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLIENTSCRIPTSDIRECTORY=/usr/lib/archivematica/MCPClient/clientScripts/

**Comment by sevein** [comment]
> ARCHIVEMATICA_MCPCLIENT_DISABLE_SEARCH_INDEXING=

This defaults to True in dev/1.8.x. Also, I think you forgot the section component. I think it should read `ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_DISABLE_SEARCH_INDEXING=True`.

**Comment by scollazo** [comment]
Configurations lke the cilentscript directory and archivematicaclientmodule should be documented in other file as suggested in #53 , we shouldn't add all available vars in the environment file.

**Comment by sevein** [comment]
The environment variables that are truly necessary can be found here: https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/defaults/main.yml#L49-L84.

I've checked and It looks like @scollazo has introduced them so I'm closing this. We can re-open if this comes up again.
