### ISSUE TITLE
Problem: systemd scripts are not reloaded after install

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/am-packbuild#64]
For xenial and centos packages, we should tell systemd to re-read the init scripts

**Comment by sevein** [comment]
@mamedin is working on this, see #41.

**Comment by scollazo** [comment]
Done in #68

**Comment by sevein** [comment]
@scollazo wouldn't be better to update #41?

**Comment by sevein** [comment]
Ok, #68 merged.
