### ISSUE TITLE
Problem: AM17 docs are outdated

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am-packbuild#77]
This could be also filed in the archivematica-docs repo but I want to make sure this is also captured here for more visibility.

For AM17 we need docs that explain thinks like setting up the rng service (https://github.com/artefactual-labs/am-packbuild/pull/73), using the new environment variables, etc...

@scollazo is maintaining the installation scripts here: https://gist.github.com/scollazo/4bd044ced115a09370274e157cc5536a. That could be used as a reference to make sure that our docs are up to date.

**Comment by sevein** [comment]
@scollazo your script isn't installing the externals. Should we add them?

**Comment by scollazo** [comment]
The scripts have been updated
