### ISSUE TITLE
Problem: pip can't download sources for metsrw=0.2.0

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/am-packbuild#84]
While running 

<pre>
pip download -d lib --no-binary :all: -r requirements.txt
</pre>

I got this:
<pre>
  Could not find a version that satisfies the requirement metsrw==0.2.0 (from -r requirements/base.txt (line 23)) (from versions: 0.1.0, 0.1.1)
No matching distribution found for metsrw==0.2.0 (from -r requirements/base.txt (line 23))
</pre>

**Comment by sevein** [comment]
@scollazo AM17 label added.
