### ISSUE TITLE
Problem: rng-tools is a runtime dependency , not a build one

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/am-packbuild#87]
Rng-tools is a daemon that gathers entropy, and makes gpg key generation faster. Is listed as a build-depend here:

https://github.com/artefactual-labs/am-packbuild/blob/master/debs/trusty/archivematica-storage-service/debian-storage-service/control#L14

But it should be in the Depends: list instead

**Comment by sevein** [comment]
Added label AM17.

**Comment by sevein** [comment]
This is related to #89.

**Comment by scollazo** [comment]
Fixed in #95
