### ISSUE TITLE
Problem: siegfried 1.7.6 not available yet in /1.7.x/centos-extras

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am-packbuild#91]
Perhaps other packages from extra need to be updated too.

**Comment by scollazo** [comment]
siegfried rpm has been added to the repo.

**Comment by scollazo** [comment]
Package is available at https://packages.archivematica.org/1.7.x/centos-extras/siegfried-1.7.6-1.el7.centos.x86_64.rpm , closing
