### ISSUE TITLE
Problem: selinux configuration

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/am-packbuild#97]
Some selinux configurations needs to be tweaked in order for archivematica to work

The archivematica-docs needs a new section that describes selinux configuration steps that are required during installation

**Comment by scollazo** [comment]
setsebool -P clamscan_read_user_content 1

**Comment by nickwilkinson** [comment]
Hi @scollazo can you please make a PR on the archivematica docs to add an selinux section to the admin manual?

**Comment by scollazo** [comment]
Created https://github.com/artefactual/archivematica-docs/pull/72

**Comment by scollazo** [comment]
Closing, the selinx instructions have been added to the docs long ago
